## cachematrix.R
##
## This program allow the using of cached inverted matrix, for a performance purpose.
##
## Two functions are availables : 
## makeCacheMatrix(x) : to create a cached matrix from an existing matrix
## cacheSolve(x, ...) : to calculate or recover the cached inverted matrix
##
## Usage
## > myMatrix<-matrix(1:4,2,2)
## > myMatrix
## [,1] [,2]
## [1,]    1    3
## [2,]    2    4
## > mcMat <- makeCacheMatrix(myMatrix)
## > cacheSolve(mcMat)
## [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## > cacheSolve(mcMat)
## getting cached data
## [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5

## makeCacheMatrix : creates a cached inverted matrix from the given one
## x : the given matrix to create the cached one from (x must be invertible)
makeCacheMatrix <- function(x = matrix()) {
  s<-NULL
  set<-function(y){
    x<<-y
    s<<-NULL
  }
  get<-function() x
  setsolve<-function(solve)s<<-solve
  getsolve<-function()s
  list(set=set, get=get,setsolve=setsolve,getsolve=getsolve)
}

## cacheSolve : invert a given cached matrix, the inverted matrix could be calculated or recovered from a cached value
## x : a matrix generated by the makeCacheMatrix function
cacheSolve <- function(x, ...) {
  s<-x$getsolve()
  if(!is.null(s)){
      message("getting cached data")
      return(s)
  }
  data<-x$get()
  s<-solve(data)
  x$setsolve(s)
  s
}